# Generated by Django 5.2.8 on 2025-12-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='순위')),
                ('product_name', models.CharField(max_length=500, verbose_name='상품명')),
                ('url', models.URLField(unique=True, verbose_name='상품URL')),
                ('seller_name', models.CharField(default='-', max_length=100, verbose_name='상호')),
                ('biz_no', models.CharField(default='-', max_length=50, verbose_name='사업자번호')),
                ('contact', models.CharField(default='-', max_length=50, verbose_name='연락처')),
                ('crawled_at', models.DateTimeField(auto_now=True, verbose_name='수집일시')),
            ],
            options={
                'verbose_name': '쿠팡 판매자 데이터',
                'verbose_name_plural': '쿠팡 판매자 데이터 목록',
            },
        ),
    ]
