# Generated by Django 5.2.8 on 2025-12-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='책 제목')),
                ('price', models.CharField(max_length=50, verbose_name='가격')),
                ('rating', models.CharField(max_length=50, verbose_name='평점')),
                ('stock', models.CharField(max_length=50, verbose_name='재고 상태')),
                ('url', models.URLField(unique=True, verbose_name='상세 URL')),
                ('crawled_at', models.DateTimeField(auto_now=True, verbose_name='수집일시')),
            ],
            options={
                'verbose_name': '수집된 책 데이터',
                'verbose_name_plural': '수집된 책 데이터 목록',
            },
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
